server:
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  thymeleaf:
      prefix: classpath:templates/
      suffix: .html

  batch:
    jdbc:
      initialize-schema: always
    post-count-threshold: 10


  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      schema-locations:
        - classpath:db/table.sql
      data-locations:
        - classpath:db/data.sql
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: true

application:
  security:
    jwt:
      secret-key: 0YLkkTt8BMSJIwLyR6GSgaCgDcbE5tbzawnTNT6d2EUEECeWm0KpLYVxXKTezwPL
      expiration: 3600000  # 1 hour
      #expiration: 1  # 1 milliSec
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    '[com.snowball.board]': DEBUG
    '[org.hibernate.type]': TRACE
    '[org.springframework.batch]': DEBUG
